image: Visual Studio 2017
configuration: Release
platform: Any CPU
  
install:
- ps: $env:build_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
- ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"
- git submodule update --init

dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  version: $(build_version)
  package_version: $(build_version)
#  file_version: $(APPVEYOR_BUILD_VERSION)

before_build:
- cmd: dotnet restore --verbosity m

build:
  project: package.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: del lib\*.nupkg
- cmd: NuGet pack

before_test:
- choco install opencover.portable
- choco install codecov
  
test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --framework net47 --verbosity q"

after_test:
- codecov -f "results.xml" 


artifacts:
- path: 'Unity.*.nupkg'
  name: 'Unity'
  
