image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - ps: $env:build_version = (Select-Xml -Path ".\Package.nuspec" -XPath "/package/metadata/version" | Select-Object -ExpandProperty Node).InnerText
  - ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"
  - cmd: git submodule update --init

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore --verbosity q

build:
  project: package.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: del lib\*.nupkg
- cmd: NuGet pack

test_script:
- cmd: dotnet test --framework net47 --configuration Release --verbosity q

artifacts:
- path: 'Unity.*.nupkg'
  name: 'Unity'
